### PR TITLE
fix: escape html characters

### LINKED ISSUE #2: More robust telegram html handling
We currently output message with some styles through telegram html

Image

But the html handling is quite fragile -- whenever there is an accidental `<>`, the telegram will fail to parse and thus won't send the message.

This was first discovered by @HuSharp through #1 . I think we should implement a more structured way to escape the html symbols in the raw message.

### PR DESCRIPTION
**Pull request by MikeWalrus**
Tested with https://english.stackexchange.com/questions/255262/what-is-the-name-of-the-symbols-and .

fixes #2 .

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -100,9 +100,9 @@ async fn gemini_api_request(
     if response.status_code() != 200 {
         let error_text = response.text().await?;
         return Err(Error::from(format!(
-            "Gemini API failed: Status {}, Error: {}",
```
Comment (XiangpengHao) [inline src/utils.rs:103]: I think those fmt changes are inconsistent with my local rustmft

**Comment by XiangpengHao** [comment]
Thank you @MikeWalrus
